/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LabService } from "../lab.service";
import { LabCreateInput } from "./LabCreateInput";
import { Lab } from "./Lab";
import { LabFindManyArgs } from "./LabFindManyArgs";
import { LabWhereUniqueInput } from "./LabWhereUniqueInput";
import { LabUpdateInput } from "./LabUpdateInput";
import { ComputerFindManyArgs } from "../../computer/base/ComputerFindManyArgs";
import { Computer } from "../../computer/base/Computer";
import { ComputerWhereUniqueInput } from "../../computer/base/ComputerWhereUniqueInput";

export class LabControllerBase {
  constructor(protected readonly service: LabService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Lab })
  async createLab(@common.Body() data: LabCreateInput): Promise<Lab> {
    return await this.service.createLab({
      data: data,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Lab] })
  @ApiNestedQuery(LabFindManyArgs)
  async labs(@common.Req() request: Request): Promise<Lab[]> {
    const args = plainToClass(LabFindManyArgs, request.query);
    return this.service.labs({
      ...args,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Lab })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async lab(@common.Param() params: LabWhereUniqueInput): Promise<Lab | null> {
    const result = await this.service.lab({
      where: params,
      select: {
        capacity: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Lab })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLab(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() data: LabUpdateInput
  ): Promise<Lab | null> {
    try {
      return await this.service.updateLab({
        where: params,
        data: data,
        select: {
          capacity: true,
          createdAt: true,
          id: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Lab })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLab(
    @common.Param() params: LabWhereUniqueInput
  ): Promise<Lab | null> {
    try {
      return await this.service.deleteLab({
        where: params,
        select: {
          capacity: true,
          createdAt: true,
          id: true,
          location: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/computers")
  @ApiNestedQuery(ComputerFindManyArgs)
  async findComputers(
    @common.Req() request: Request,
    @common.Param() params: LabWhereUniqueInput
  ): Promise<Computer[]> {
    const query = plainToClass(ComputerFindManyArgs, request.query);
    const results = await this.service.findComputers(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        lab: {
          select: {
            id: true,
          },
        },

        specs: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/computers")
  async connectComputers(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: ComputerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      computers: {
        connect: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/computers")
  async updateComputers(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: ComputerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      computers: {
        set: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/computers")
  async disconnectComputers(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: ComputerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      computers: {
        disconnect: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }
}
