/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ComputerService } from "../computer.service";
import { ComputerCreateInput } from "./ComputerCreateInput";
import { Computer } from "./Computer";
import { ComputerFindManyArgs } from "./ComputerFindManyArgs";
import { ComputerWhereUniqueInput } from "./ComputerWhereUniqueInput";
import { ComputerUpdateInput } from "./ComputerUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class ComputerControllerBase {
  constructor(protected readonly service: ComputerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Computer })
  async createComputer(
    @common.Body() data: ComputerCreateInput
  ): Promise<Computer> {
    return await this.service.createComputer({
      data: {
        ...data,

        lab: data.lab
          ? {
              connect: data.lab,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        lab: {
          select: {
            id: true,
          },
        },

        specs: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Computer] })
  @ApiNestedQuery(ComputerFindManyArgs)
  async computers(@common.Req() request: Request): Promise<Computer[]> {
    const args = plainToClass(ComputerFindManyArgs, request.query);
    return this.service.computers({
      ...args,
      select: {
        createdAt: true,
        id: true,

        lab: {
          select: {
            id: true,
          },
        },

        specs: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Computer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async computer(
    @common.Param() params: ComputerWhereUniqueInput
  ): Promise<Computer | null> {
    const result = await this.service.computer({
      where: params,
      select: {
        createdAt: true,
        id: true,

        lab: {
          select: {
            id: true,
          },
        },

        specs: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Computer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateComputer(
    @common.Param() params: ComputerWhereUniqueInput,
    @common.Body() data: ComputerUpdateInput
  ): Promise<Computer | null> {
    try {
      return await this.service.updateComputer({
        where: params,
        data: {
          ...data,

          lab: data.lab
            ? {
                connect: data.lab,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          lab: {
            select: {
              id: true,
            },
          },

          specs: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Computer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteComputer(
    @common.Param() params: ComputerWhereUniqueInput
  ): Promise<Computer | null> {
    try {
      return await this.service.deleteComputer({
        where: params,
        select: {
          createdAt: true,
          id: true,

          lab: {
            select: {
              id: true,
            },
          },

          specs: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: ComputerWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        bookingDate: true,

        computer: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        duration: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: ComputerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateComputer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: ComputerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateComputer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: ComputerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateComputer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
